players:
  names:
    - jakub
    - computer1
    - computer2
    - random1
  types:
    - human
    - ai1
    - ai2
    - random
init_cards: 5
symbols:
  HEART: "ğŸ§¡"
  BELL: "ğŸŸ¡"
  ACORN: "â™§"
  LEAF: "ğŸ‚"
  VII: "7"
  VIII: "8"
  IX: "9"
  X: "10"
  UNDER: "â››"
  OVER: "ğŸ”º"
  KING: "ğŸ‘‘"
  ACE: "A"
  __PREFIX__: ""
  __SUFFIX__: ""
  __DELIMITER__: ""
